name: Build for Windows/Linux
on: [push]
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pytest pyinstaller
      # - run: pytest
      - run: pyinstaller --onefile QEMU启动器.py
      - uses: actions/upload-artifact@v4  # 自动上传生成的可执行文件
        with:
          name: win-artifact
          path: dist/QEMU启动器.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install pytest pyinstaller
      # - run: pytest
      - name: Build with PyInstaller
        run: pyinstaller --onefile QEMU启动器.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: dist/QEMU启动器